# Generated by Django 5.2.4 on 2026-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_risk', models.FloatField(default=0.0)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
